[package]
name = "cpq"
version = "0.2.0"
edition = "2021"
description = "A Concurrent Priority Queue implemented in Safe Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/cpq"

[dependencies]
parking_lot = "0.12"